### ISSUE TITLE
Potential bug in color option in dySeries

### ISSUE THREAD

**Issue by ramnathv** [rstudio/dygraphs#35]
The following code from the tutorial

```r
dygraph(lungDeaths, main = "Deaths from Lung Disease (UK)") %>%
  dySeries("mdeaths", drawPoints = TRUE, color = "blue") %>%
  dySeries("fdeaths", stepPlot = TRUE, fillGraph = TRUE, color = "red")
```

does not result in the specified colors for the two series. Specifying `dyOptions(colors = c('red', 'blue'))` works. Is this a bug?

**Comment by jjallaire** [comment]
That was a bug which we fixed in the last release. What version are you running? (current CRAN version is 0.4.1)

**Comment by jjallaire** [comment]
Re-opened pending your verification that an older version is the issue.

**Comment by ramnathv** [comment]
I am running 0.4.1. I did a fresh install from github and the issue still persists.

**Comment by jjallaire** [comment]
Interesting, I can't reproduce locally. What's your platform and
sessionInfo?

On Feb 19, 2015, at 4:11 PM, Ramnath Vaidyanathan <notifications@github.com>
wrote:

I am running 0.4.1. I did a fresh install from github and the issue still
persists.

—
Reply to this email directly or view it on GitHub
<https://github.com/rstudio/dygraphs/issues/35#issuecomment-75159032>.

**Comment by ramnathv** [comment]
Here is my `sessionInfo()`. I ran it from the R GUI to make sure I am running a fresh session.

```
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] dygraphs_0.4.1 devtools_1.7.0

loaded via a namespace (and not attached):
 [1] digest_0.6.8      grid_3.1.2        htmltools_0.2.6  
 [4] htmlwidgets_0.3.2 lattice_0.20-29   magrittr_1.5     
 [7] RJSONIO_1.3-0     xts_0.9-7         yaml_2.1.13      
[10] zoo_1.7-11       
```

**Comment by ramnathv** [comment]
The same bug is seen on this page of the documentation

http://rstudio.github.io/dygraphs/gallery-series-options.html

The stepplot at the bottom should be colored red, whereas it is blue in the plot on the page.

**Comment by ramnathv** [comment]
Digging a little deeper, I saved the output to an object `x` and inspected it.

```r
x$x$attrs$colors
# "blue" "blue" "red"  "red" 
```

I think the bug fix recycling colors for the single color case messes with the multi color situation.

**Comment by jjallaire** [comment]
Okay, that makes complete sense. The change I was trying to make was to ensure that the colors array is at least 2 elements long (dygraphs doesn't like it when it's one). I should probably be doing this on the JS side rather than the R side though. Should have a fix soon!

**Comment by jjallaire** [comment]
This commit should fix the issue: https://github.com/rstudio/dygraphs/commit/f275944b30302918811293b4e820212034a43a72

Let me know if this does it for you.

**Comment by ramnathv** [comment]
Nice. This does fix it. Thanks @jjallaire.
